### ISSUE TITLE
RFE: Support Google Chat

### ISSUE THREAD

**Issue by TJM** [larderdev/kubewise#17]
I like the looks of this project, but unfortunately our corporate chat platform is Google Chat. It supports basic APIs with tokens to push messages in, so I think it would be fairly straightforward to support.

**Comment by dtuite** [comment]
Good suggestion @TJM. Would you mind filling this [2 min survey out](https://forms.gle/H5VydMArv9k6XfoY6) so I can track these requests for new chat integrations please?

If you add your email address I'll send you an email when Google Chat is added.

**Comment by TJM** [comment]
Done, thanks.

**Comment by TJM** [comment]
https://developers.google.com/hangouts/chat/how-tos/webhooks

For what its worth, we have done some basic tests with curl and it seems pretty simple. The GO API https://godoc.org/google.golang.org/api/chat/v1 is *fantastically* over complicated for what we are trying to accomplish. It may have a simple "send a message via webhook" mode, but I could not find it. I am not a developer tho :)

**Comment by dtuite** [comment]
@TJM I have this working locally now. It's not released yet but it can be soon hopefully. Take a look in the pull request #19 please and let me know what you think of the screenshot.

**Comment by dtuite** [comment]
Initial implementation released in version 0.4.0. README updated.
