### ISSUE TITLE
Add secrets checksum (updating webhook url doesn't restart pod)

### ISSUE THREAD

**Issue by TJM** [larderdev/kubewise#36]
I implemented this, then we decided we wanted to change which channel the output went to. I updated the webhook URL in the values, but the change did not take effect because there was nothing tying the change in the secret to the deployment.

https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

**Comment by dtuite** [comment]
Fixed and released in chart version `0.7.0`.
