### ISSUE TITLE
Use explicit tag rather than chart release to allow forking

### ISSUE THREAD

**Issue by cep21** [larderdev/kubewise#4]
See https://github.com/fluxcd/flux/tree/master/chart/flux as a good example.

Add the helm value
```
image:
  tag: 0.1.0
```

Then use that inside `deployment.yaml`.  This will allow people to fork your repository and use their own images.

**Comment by dtuite** [comment]
Hi Jack. I believe I've done what you're looking for in this pull request: #7 

Would you mind reviewing before I merge it please?

Thanks for the suggestion.
