### ISSUE TITLE
docker image 0.11.11 was not published?

### ISSUE THREAD

**Issue by TJM** [larderdev/kubewise#54]
According to: https://github.com/RoadieHQ/kubewise/blob/fb5339c142bf09f03e4883f4472b2251a930aa2e/helm_chart/values.yaml#L7-L8

... the image should be `us.gcr.io/larder-prod/kubewise:0.11.11` ... but I can't seem to pull that:

```
$ docker pull us.gcr.io/larder-prod/kubewise:0.11.11
Error response from daemon: manifest for us.gcr.io/larder-prod/kubewise:0.11.11 not found: manifest unknown: Failed to fetch "0.11.11" from request "/v2/larder-prod/kubewise/manifests/0.11.11".
```

Last published version was 0.11.8:
![Screen Shot 2021-02-08 at 12 32 43 PM](https://user-images.githubusercontent.com/1641316/107271807-fa359e80-6a09-11eb-972a-c345fca1c87e.png)

**Comment by padraigobrien** [comment]
Hey TJM, thanks for flagging this with us, let me dig into where 0.11.11 is and I will get back to you.

**Comment by dtuite** [comment]
@TJM The image is on docker hub now: https://hub.docker.com/repository/docker/roadiehq/kubewise

If you change your helm values to

```yaml
image:
  repository: roadiehq/kubewise
  tag: 0.11.11
```

It should work.

Apologies for the confusion. I must have forgotten to update the helm chart with the correct repository when I moved to Docker Hub.

**Comment by TJM** [comment]
Quite frankly, we are trying to avoid using DockerHub (docker.io) directly due to their rate limiting. We probably didn't get the change because we already have to override the "repository" to go through Artifactory (`gcr.artifactory.company.com/larder-prod/kubewise`)... we can just change the override to dockerhub, I guess :)
