### ISSUE TITLE
Support for legacy Helm v2

### ISSUE THREAD

**Issue by nodesocket** [larderdev/kubewise#55]
Does kubewise work with Helm version 2? We, for various reasons cannot upgrade our Helm to version 3. Will this work with Helm v2?

The first thing that is breaking trying to install is `Error: apiVersion 'v2' is not valid. The value must be "v1"`. Perhaps a legacy Helm v1 version can be maintained?

**Comment by dtuite** [comment]
Hi @nodesocket . Helm 2 is currently not supported and there are no plans to add support. Sorry!

**Comment by nodesocket** [comment]
I could be wrong, but typically everything that works on Helm 3 works on Helm 2. The big breaking thing is just setting the `apiVersion` here:

https://github.com/RoadieHQ/kubewise/blob/master/helm_chart/Chart.yaml#L1

Would you be open to hosting a Helm 2 supported Chart?

**Comment by nodesocket** [comment]
We upgraded to Helm 3.
